#!/usr/bin/python3
import requests, json, os, sys

HOSTNAME = "localhost"
PORT = "8080"

url = "http://" + HOSTNAME + ":" + PORT + "/cfginfo"

response = requests.get(url)

if(response.status_code == 200):
    return_data = response.json()
    # print configfiles per line
    with open('grading/cli_tests/obtained_cfginfo.txt', 'w') as f:
        for config_file in return_data.get('files'):
            f.write(config_file + "\n")
    exit(0)
else:
    exit(1)